### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ghost** [GideonWolfe/canvas-tui#3]
git cloned the directory, from there I ran
`go build` and get the following output
`announcements.go:16:3: cannot find package "github.com/gizak/termui/v3" in any of:
	/usr/lib/go-1.14/src/github.com/gizak/termui/v3 (from $GOROOT)
	/home/m00/go/src/github.com/gizak/termui/v3 (from $GOPATH)
announcements.go:17:3: cannot find package "github.com/gizak/termui/v3/widgets" in any of:
	/usr/lib/go-1.14/src/github.com/gizak/termui/v3/widgets (from $GOROOT)
	/home/m00/go/src/github.com/gizak/termui/v3/widgets (from $GOPATH)
announcements.go:15:3: cannot find package "github.com/grokify/html-strip-tags-go" in any of:
	/usr/lib/go-1.14/src/github.com/grokify/html-strip-tags-go (from $GOROOT)
	/home/m00/go/src/github.com/grokify/html-strip-tags-go (from $GOPATH)
fetchAnnouncements.go:8:3: cannot find package "github.com/spf13/viper" in any of:
	/usr/lib/go-1.14/src/github.com/spf13/viper (from $GOROOT)
	/home/m00/go/src/github.com/spf13/viper (from $GOPATH)`

not terribly certain what exactly is going on here. This looks like a real neat piece of software and id like to try it out, but at the moment this is preventing me. Using 

`go run`
also returns 
`no go files listed`

**Comment by GideonWolfe** [comment]
I think you need to install those go modules. For each url listed there, run `go get <url>` and see if that fixes it.

**Comment by GideonWolfe** [comment]
There are a few things I would like to clean up here to get it working better. I'm not enrolled in any courses currently which makes it a bit difficult to test.

**Comment by ghost** [comment]
Was able to install but now have the following new issues:
`./canvas-tui 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x87d73e]

goroutine 1 [running]:
main.fetchCourses(0x0)
	/home/m00/Desktop/Linux/canvas-tui/fetchCourses.go:153 +0x3ae
main.main()
	/home/m00/Desktop/Linux/canvas-tui/main.go:172 +0xec
`

then if I try to run as sudo
`sudo ./canvas-tui
[sudo] password for m00: 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/gizak/termui/v3/widgets.(*Plot).renderBraille(0xc0000d8500, 0xc00040ff20, 0x6, 0x28, 0x7e, 0x2f, 0x4059000000000000)
	/home/m00/go/src/github.com/gizak/termui/v3/widgets/plot.go:99 +0x703
github.com/gizak/termui/v3/widgets.(*Plot).Draw(0xc0000d8500, 0xc00040ff20)
	/home/m00/go/src/github.com/gizak/termui/v3/widgets/plot.go:223 +0x123
github.com/gizak/termui/v3.(*Grid).Draw(0xc0003de0d0, 0xc00040ff20)
	/home/m00/go/src/github.com/gizak/termui/v3/grid.go:157 +0x1af
github.com/gizak/termui/v3.(*Grid).Draw(0xc0003de9c0, 0xc00040ff20)
	/home/m00/go/src/github.com/gizak/termui/v3/grid.go:157 +0x1af
github.com/gizak/termui/v3.Render(0xc000154910, 0x1, 0x1)
	/home/m00/go/src/github.com/gizak/termui/v3/render.go:25 +0x285
main.main()
	/home/m00/Desktop/Linux/canvas-tui/main.go:283 +0x110e
`
